#choco feature enable -n=allowGlobalConfirmation
choco install vscode 
choco install firefox 
choco install python3 
choco install 7zip 
choco install git 
choco install paint.neY 
choco install foxitreader 
choco install curl 
choco install k-litecodecpackfull 
choco install amd-ryzen-chipset 
choco install rust 
choco install rustdesk.portablY 
choco install wiztree 
choco install onlyoffice 
choco install equalizerapo 
choco install obsidian 
choco install keepassxc 
choco install kdenlive 

Write-Host "Listo el pollo, apreta cualquier cosa para terminar"
$input = Read-Host
# SIG # Begin signature block
# MIIFhQYJKoZIhvcNAQcCoIIFdjCCBXICAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUPFJp/3suh+tNRdkAAusSpxp6
# 4ZmgggMYMIIDFDCCAfygAwIBAgIQNu0W+u0DQIJNRPnc/qYBHjANBgkqhkiG9w0B
# AQUFADAiMSAwHgYDVQQDDBdQb3dlclNoZWxsIENvZGUgU2lnbmluZzAeFw0yNDA2
# MjUyMTIzMThaFw0yNTA2MjUyMTQzMThaMCIxIDAeBgNVBAMMF1Bvd2VyU2hlbGwg
# Q29kZSBTaWduaW5nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwjLU
# U8QVayC9V5eHu8WjRUIxN7hMOyH7iF1w3IksMzojLjLXtvIVl2oFbl27GDUcWJcB
# lGs/+Lg6GvCdRW7gu8HPczUIrv8epeNbmoegmp6ZVGFsSvmFRifZf3Hwc66xy8Gk
# 6gTg8LmkPTZSGRM26l1a0ldW5rHRh7Wir5D6/IW5FrVoJYoISzZl9dWnDfeqck+6
# rgsiA5u8bEIEgqQU8PidLxC+Btoii+1cH67U7UbvTcKdKE3At9rRSOLKECfTNPTK
# tA2x6qPV0qc4+Q5NCy7oXaLoacsykzvXyPW0SCGlDA4q1R3Qvx2mJmBjI5UyBaoI
# oxi0wNU8rrTYa+zaGQIDAQABo0YwRDAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAww
# CgYIKwYBBQUHAwMwHQYDVR0OBBYEFHgF7wvT8jubS02Sdivr2Ec2hRvnMA0GCSqG
# SIb3DQEBBQUAA4IBAQBLuU0joHTDhDF+iK1FG3H5Am72dorLzrJHr0oeMSg5jTCg
# LdFQybKrdCXy6YjRuyeXmyIBlIhNCW9Dncmtr+BahNFQQSV1ZFkjUrVcDm+NHX+x
# Ppyia+m8z6K8cDWLd2vJcBR2KUSZsNVLTP/+VXw/gS2TVwwk2yG0PqMCjevaA+LW
# V1+OlcYRqDd1XXoBxXSAZ5UUoE4Si8Qu78W2QiOYgnXduK1gtuurZtkkRBoZPfu6
# TPIsIwgblEuV9B6asefKKKJaGzVwtTXkrd5V7gcO/Jph/8UQlCiBrMQaf8Xe0Sjg
# JrjLXGKGkl+qQM3gIr07PE+Ulz6dbl5Ja10G5Ru2MYIB1zCCAdMCAQEwNjAiMSAw
# HgYDVQQDDBdQb3dlclNoZWxsIENvZGUgU2lnbmluZwIQNu0W+u0DQIJNRPnc/qYB
# HjAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG
# 9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIB
# FTAjBgkqhkiG9w0BCQQxFgQUIS9ZHW3WvZkMLVCZfaNoUG3r8W8wDQYJKoZIhvcN
# AQEBBQAEggEAkNdUsQxy7ozzLS5hLUgOozfSEQiPdJXRvRcqNHBv0FaMVd3jD/b6
# MMk+FXeGJW0qKMEdrV3c8x4/g8nsVZba2bUDnqGInQZqjKT2BSI9jQNK3rixDSh7
# ICRq8VRBlTtEnR/9qGspuBMQE7AUT282y4TypOzs2/jsVGtVmIOWeuVfQtOIgw8/
# segTofAfJvQR+gGZsP5oOXlYeIhmS/M9r/qP6sZOEJ0lOSqz2c5FgaE+Uc5GmY2Q
# qu+eMMjSRcLfa+/hHnSDukM5sMQW+iHY0mmQCWffmNS64laVeQmwvASi1URzS/Jy
# 9PUTJLAaktm9kFE8agAstEHmjktf4KpaWQ==
# SIG # End signature block
